version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend


  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "yourStrongPassword123"]
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-prisma-app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             npm run build &&
             node dist/index.js"

volumes:
  pgdata:

networks:
  backend:
